// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAnyNhj9HIQekzL8BYU5sntm_OtsMQyME',
    appId: '1:133161286028:web:a74d1365990bdc9694fea9',
    messagingSenderId: '133161286028',
    projectId: 'tsa-29-firebase2',
    authDomain: 'tsa-29-firebase2.firebaseapp.com',
    storageBucket: 'tsa-29-firebase2.appspot.com',
    measurementId: 'G-32W5THCKJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2D37em9_5LtAjV1QUIFBCCF3dWo6jx14',
    appId: '1:133161286028:android:f8af9db44d670f3d94fea9',
    messagingSenderId: '133161286028',
    projectId: 'tsa-29-firebase2',
    storageBucket: 'tsa-29-firebase2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDytyl08wPpE2yf3O4STRC09Abwp_PZuSU',
    appId: '1:133161286028:ios:8e1a5e5f5e4069c394fea9',
    messagingSenderId: '133161286028',
    projectId: 'tsa-29-firebase2',
    storageBucket: 'tsa-29-firebase2.appspot.com',
    iosClientId: '133161286028-hl7sg43ag7185kfec0jhf14risbscfeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDytyl08wPpE2yf3O4STRC09Abwp_PZuSU',
    appId: '1:133161286028:ios:8e1a5e5f5e4069c394fea9',
    messagingSenderId: '133161286028',
    projectId: 'tsa-29-firebase2',
    storageBucket: 'tsa-29-firebase2.appspot.com',
    iosClientId: '133161286028-hl7sg43ag7185kfec0jhf14risbscfeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
